apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: faf-lobby-server
  name: faf-lobby-server
spec:
  podManagementPolicy: OrderedReady
  replicas: 1  # Never scale more than 1 replica. This will most probably corrupt the data.
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: faf-lobby-server
  serviceName: faf-lobby-server
  template:
    metadata:
      labels:
        app: faf-lobby-server
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8011'
        prometheus.io/path: '/'
    spec:
      initContainers:
        - name: setup
          image: brutus5000/alpine-envsubst:3
          imagePullPolicy: Always
          command: ['sh', '-c', "/config/build-config.sh"]
          envFrom:
            - configMapRef:
                name: faf-lobby-server
            - secretRef:
                name: faf-lobby-server
          volumeMounts:
            - name: pod-config
              mountPath: /pod
            - name: config-template
              mountPath: /config/config.yml.template
              subPath: config.yml.template
            - name: config-script
              mountPath: /config/build-config.sh
              subPath: build-config.sh
      containers:
      - name: faf-lobby-server
        image: faforever/faf-python-server:v1.11.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: faf-lobby-server
          - secretRef:
              name: faf-lobby-server
        ports:
        - containerPort: 8002
          protocol: TCP
        volumeMounts:
          - name: pod-config
            mountPath: /pod
      restartPolicy: Always
      volumes:
      - name: pod-config
        emptyDir: {}
      - name: config-script
        configMap:
          name: faf-lobby-server
          defaultMode: 077
      - name: config-template
        configMap:
          name: faf-lobby-server