# TODO: This volume should move to NFS so it can run on any node
# TODO: Split these down into logical chunks (replays, featured mods, maps, mods, ...)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: faf-content-pv
  labels:
    app: faf-content
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-fast-storage
  local:
    path: /opt/faf/data/content
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-id
              operator: In
              values:
                - main-01
