# TODO: This volume should move to NFS so it can run on any node

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodebb-pv
  labels:
    app: nodebb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-fast-storage
  local:
    path: /opt/faf/data/nodebb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-id
              operator: In
              values:
                - main-01
