# TODO: This volume should move to NFS so it can run on any node

apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpbb3-archive-pv
  labels:
    app: phpbb3-archive
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-fast-storage
  local:
    path: /opt/faf/data/php3-archive
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-id
              operator: In
              values:
                - main-01

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpbb3-archive-pvc
  labels:
    app: phpbb3-archive
spec:
  storageClassName: local-fast-storage
  volumeName: phpbb3-archive-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Gi
