apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-api
  labels:
    app: faf-api
data:
  # Global options
  FAF_DOMAIN: "##FAF_BASE_DOMAIN##"
  JAVA_TOOL_OPTIONS: -Xms256m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError
  
  # App options
  DATABASE_ADDRESS: mariadb
  DATABASE_NAME: faf
  DATABASE_USERNAME: faf-api
  ANOPE_DATABASE_NAME: anope
  EMAIL_FROM_ADDRESS: admin@localhost
  EMAIL_FROM_NAME: Your localhost FAF team
  GITHUB_DEPLOYMENT_ENVIRONMENT: development
  LEAGUE_DATABASE_ADDRESS: mariadb
  LEAGUE_DATABASE_NAME: faf-league
  LEAGUE_DATABASE_USERNAME: faf-api
  MAUTIC_ACCESS_TOKEN_URL: http://faf-mautic/oauth/v2/token
  MAUTIC_BASE_URL: http://faf-mautic/api
  MAUTIC_CLIENT_ID: faf-api
  NODEBB_BASE_URL: http://faf-nodebb:4567
  NODEBB_MASTER_TOKEN: 77c91a43-35dc-4628-a788-62d4f18526ab
  NODEBB_USER_ID: "1"
  PASSWORD_RESET_EMAIL_BODY: Dear {0},\n\na new password was requested for your user.\nIf you did not request a new password, please delete this email.\n\nOtherwise please click on the following link to reset your password:\n-----------------------\n{1}\n-----------------------\n\nThanks,\n-- The FA Forever team"
  PASSWORD_RESET_EMAIL_SUBJECT: FAForever - Password reset
  RECAPTCHA_ENABLED: "true"
  RECAPTCHA_SECRET: 6Lc4GmgaAAAAAKC7eg8cPZl-hNZ7dqBUZW-NmF7q
  REGISTRATION_EMAIL_BODY: Dear {0},\n\nwelcome to the FAForever community.\nPlease visit the following link to activate your FAF account:\n\n-----------------------\n{1}\n-----------------------\n\nThanks,\n-- The FA Forever team
  REGISTRATION_EMAIL_SUBJECT: FAForever - Account validation
