apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-content
  labels:
    app: faf-content
data:
  # Only for testing environments
  default.conf: |-
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
  
      #access_log  off;

  
      location / {
          root   /content;
          index  index.html index.htm;
      }

      # Access the path. If 200 is returned, Nginx can receive requests.
      location /health {
          access_log off;
          return 200;
      }
  
      # redirect server error pages to the static page /50x.html
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
