apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  labels:
    app: rabbitmq
spec:
  storageClassName: local-fast-storage
  volumeName: rabbitmq-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
