apiVersion: v1
kind: Service
metadata:
  name: unrealircd
  labels:
    app: unrealircd
spec:
  clusterIP: None
  selector:
    app: unrealircd
  ports:
    # plain text for QAI and Python client
    - name: "6667"
      port: 6667
      targetPort: 6667
    # ssl only
    - name: "6697"
      port: 6697
      targetPort: 6697
    # ssl only
    - name: "8167"
      port: 8167
      targetPort: 8167
    # Anope control port
    - name: "7000"
      port: 7000
      targetPort: 7000
