apiVersion: v1
kind: Secret
metadata:
  name: nodebb
  labels:
    app: nodebb
data:
  config.json: >-
    ewogICJ1cmwiOiAiaHR0cDovL2xvY2FsaG9zdDo0NTY3IiwKICAic2VjcmV0IjogImJhbmFuYSIsCiAgImRhdGFiYXNlIjogIm1vbmdvIiwKICAicG9ydCI6IDQ1NjcsCiAgIm1vbmdvIjogewogICAgImhvc3QiOiAibW9uZ29kYiIsCiAgICAicG9ydCI6ICIyNzAxNyIsCiAgICAidXNlcm5hbWUiOiAibm9kZWJiIiwKICAgICJwYXNzd29yZCI6ICJiYW5hbmEiLAogICAgImRhdGFiYXNlIjogIm5vZGViYiIKICB9LAogICJvYXV0aCI6IHsKICAgICJhdXRob3JpemF0aW9uVVJMIjogImh0dHA6Ly9mYWYtb3J5LWh5ZHJhOjQ0NDQvb2F1dGgyL2F1dGgiLAogICAgInRva2VuVVJMIjogImh0dHA6Ly9mYWYtb3J5LWh5ZHJhOjQ0NDQvb2F1dGgyL3Rva2VuIiwKICAgICJmYWZBcGlQcm9maWxlVVJMIjogImh0dHA6Ly9mYWYtamF2YS1hcGk6ODAxMC9tZSIsCiAgICAiaWQiOiAiZmFmLWZvcnVtIiwKICAgICJzZWNyZXQiOiAie3Rva2VuRnJvbVNjcmlwdHMtY3JlYXRlLWh5ZHJhLXRlc3QtY2xpZW50cy5zaH0iLAogICAgInNjb3BlIjogInB1YmxpY19wcm9maWxlIgogIH0KfQo=
type: Opaque
