apiVersion: v1
kind: Service
metadata:
  name: faf-user-service
  labels:
    app: faf-user-service
spec:
  selector:
    app: faf-user-service
  ports:
    - name: consumer-port
      port: 8080
      targetPort: 8080
    - name: management-port
      port: 8081
      targetPort: 8081
