apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpbb3-archive-volume
  labels:
    type: local
    app: phpbb3-archive
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/opt/faf/data/php3-archive"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpbb3-archive-pvc
  labels:
    app: phpbb3-archive
spec:
  storageClassName: manual
  volumeName: phpbb3-archive-volume
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Gi
