apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: faf-replay-server
spec:
  entryPoints:
    - replay-server
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: faf-replay-server
          port: 15000
