apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: faf-lobby-server
spec:
  entryPoints:
    - lobby-server
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: faf-lobby-server
          port: 8002
