apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: faf-website
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`##FAF_BASE_DOMAIN##`) || Host(`www.##FAF_BASE_DOMAIN##`)
      kind: Rule
      services:
        - name: faf-website
          port: 3000
  tls:
    certResolver: default
