apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: voting
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`voting.##FAF_BASE_DOMAIN##`)
      kind: Rule
      services:
        - name: voting
          port: 3000
  tls:
    certResolver: default
