apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpbb3-archive-pvc
  labels:
    app: phpbb3-archive
spec:
  storageClassName: local-fast-storage
  volumeName: phpbb3-archive-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Gi
