apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
spec:
  clusterIP: None
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
