apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  storageClassName: local-fast-storage
  volumeName: wordpress-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
